[project]
name = "humanizer"
version = "0.1.0"
description = "humanize mouse movements"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
    "torch>=2.9.1",
    "flask>=3.0.0",
    "tqdm>=4.67.1",
]
